-- Add server-enforced anti-cheat fields to attempts.
ALTER TABLE "Attempt" ADD COLUMN IF NOT EXISTS "tabSwitchCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Attempt" ADD COLUMN IF NOT EXISTS "tabSwitchLog" JSONB NOT NULL DEFAULT '[]';
ALTER TABLE "Attempt" ADD COLUMN IF NOT EXISTS "fullscreenExits" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Attempt" ADD COLUMN IF NOT EXISTS "fullscreenLog" JSONB NOT NULL DEFAULT '[]';
ALTER TABLE "Attempt" ADD COLUMN IF NOT EXISTS "warningCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Attempt" ADD COLUMN IF NOT EXISTS "isFlagged" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Attempt" ADD COLUMN IF NOT EXISTS "flagReason" TEXT;
